export const socialProfileField = [
  'website',
  'portfolio',
  'github',
  'gitbook',
  'medium',
  'orcid',
  'skype',
  'bluesky',
  'threads',
  'x',
  'discord',
  'dribbble',
  'behance',
  'stack overflow',
  'gitlab',
  'quora',
  'facebook',
  'instagram',
  'wechat',
  'hugging face',
  'kaggle',
  'youtube',
  'tiktok',
  'signal',
  'telegram',
  'whatsapp',
  'paypal',
  'product hunt',
  'artstation',
  'codepen',
  'fiverr',
  'hashnode',
  'pluralsight',
  'researchgate',
  'imdb',
  'qwiklabs',
  'google play',
  'tumblr',
  'tripadvisor',
  'yelp',
  'slack',
  'flickr',
  'reverbnation',
  'deviantart',
  'vimeo',
  'reddit',
  'pinterest',
  'blogger',
  'spotify',
  'bitcoin',
  'app store',
  'wordpress',
  'leetcode',
  'codechef',
  'codecademy',
  'codeforces',
  'vsco',
  'snapchat',
  'upwork',
  'geeksforgeeks',
  'google scholar',
  'line',
  'tryhackme',
  'coursera',
  'proton mail',
  'hackerearth',
  'codewars',
  'hack the box',
  'bitbucket',
  'gitea',
  'xing',
  '500px',
  'dev.to',
  'hackerrank',
  'tencent qq',
  'ethereum',
  'stopstalk',
  'substack',
  'toptal',
  'polywork',
  'replit',
  'credly',
  'figma',
  'gmail',
  'tableau',
  'npm',
  'hackerone',
  'freelancer',
  'datacamp',
  'mastodon',
  'letterboxd',
  'zoom',
  'audioboom',
  'soundcloud',
  'soundcharts',
  'kakaotalk',
  'salesforce',
  'itch.io',
  'sololearn',
  'opensea',
  'devpost',
  'linktree',
  'codingame',
  'coding ninjas',
  'unsplash',
  'indeed',
  'handshake',
  'steam',
  'google',
  'calendly',
  'angellist',
  'deezer',
  'flowcv',
  'khan academy',
  'udemy',
  'udacity',
  'twitch',
  'trello',
  'evernote',
  'canva',
  'etsy',
  'google maps',
  'google podcasts',
  'apple podcasts',
  'stitcher',
  'amazon music',
  'iheartradio',
  'tunein',
  'pocket casts',
  'pandora',
  'youtube music',
  'tidal',
  'bandcamp',
  'scopus',
  'disco',
]

export type SocialProfile = (typeof socialProfileField)[number]
